.. vim: syntax=rst

-  Business Case

-  Technical Details

-  Data Requirements

-  Pipeline Steps

-  Expected results

-  How to use - NEEDED - parked for now - Step by step how to on RC platform

Business case
-------------

5G implementation is rapidly increasing globally, with around `70 countries <https://www.statista.com/chart/23194/5g-networks-deployment-world-
map/>`__ reporting 5G network coverage in June 2022, up from just 38 in mid-2020.
This is projected to continue to grow.

One challenge faced by 5G network providers is weather-related disruption which causes radio link failure (RLF).
These can prove expensive and impact their ability to provide their ultra-reliable low latency communication services.
It affects the maintenance of network speeds and latency with industry standards and it provides a poor experience for customers relying on the
network

Using machine learning to predict and monitor RLF caused by weather conditions can prove impactful, and generate more consistent, reliable 5G service.

Technical Details
-----------------

Bernardo

Data requirements
-----------------

For this project, the datasets used contain six files from three sources:

-  Historical Tower radio-link:

   -  rl-sites.csv: This file contains radio link sites ids.

   -  rl-kpis.csv: This file contains 5G configuration features.

-  Tower Configuration Data:

   -  distances.csv: This file is a correlation matrix between all sites including weather and 5G towers.

-  Weather Data:

   -  met-stations.csv: This file contains weather stations.

   -  met-real.csv: This file contains weather stations ids.

   -  met-forecast.csv: This file contains a 5-days forecasting table for a given station.

Pipeline Steps
--------------

In the pipeline on RapidCanvas, the following steps were carried out.

-  **Data Preparations Transformation**

..

   In this recipe, the input datasets are made ready for the next recipes.

-  **Forecast Weather Transformation:**

..

   In this transformation, the forecasting datasets are extracted.

-  **Merged Dataset Transformation:**

..

   In this recipe, the weather datasets are combined with 5G configuration datasets in one single dataframe.

-  **Combine Training Dataset Transformation:**

..

   In this transformation, training datasets are chosen

-  **Data Cleaning Transformation:**

..

   In this step, the data is cleaned and made consistent for use.

-  **Data Transformation Transformation:**

..

   Here, transformation techniques are used to convert all datasets into numerical data.

-  **Feature Engineering Transformation:**

..

   In this part of the pipeline, feature engineering techniques are used with features such as datetime features and polynomial features.

-  **Feature Selection Transformation:**

..

   Feature selection techniques are used to reduce features variance.

-  **Modeling Transformation**

..

   This step is dedicated to building a decision tree model and fine tuning it.

-  **Prediction Transformation**

..

   In this transformation, the model and inference validation data is evaluated.

Expected Results
----------------

Using these transformations, the following results can be achieved:

-  Predicting radio-link failure (RLF) events 5 days ahead of weather-related events

-  Creating live daily RLF predictions for each individual tower on the network

-  Producing a live dashboard displaying predicted status for each tower on the network.
